# creating numpy / n-d arrays

In [16]:
import numpy as np

In [17]:
array1 = np.array([1, 2, 3, 4, 5])

In [18]:
array1

array([1, 2, 3, 4, 5])

In [19]:
type(array1)

numpy.ndarray

In [20]:
arr2 = np.array([[1,2,3], [3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [21]:
type(arr2)

numpy.ndarray

In [22]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr6 = np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [26]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## properties & Attributes
# 1.Shape
# 2.nDim
# 3.size
# 4.Itemsize
# 5.Dtype
# 6.astype()

# Shape

In [27]:
array1.shape


(5,)

In [30]:
arr9 = np.array(([[[1,2], [3,4]], [[5,6], [7,8]]]))
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
arr9.shape

(2, 2, 2)

# nDim

In [32]:
arr9.ndim

3

# Size

In [33]:
arr9.size

8

In [34]:
arr7.size

10

# Item size

In [35]:
arr9.itemsize

8

In [36]:
arr7.itemsize

8

# Dtype

In [37]:
arr9.dtype

dtype('int64')

# astype

In [38]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

# Numpy array vs Python array

# List vs Array
1. Faster
2. Convenient
3. Less memory

In [39]:
lista = range(100)
arr11 = np.arange(100)

In [40]:
import sys

In [41]:
print(sys.getsizeof(87)*len(lista))

2800


In [43]:
print(arr11.itemsize*arr11.size)

800


In [44]:
import time

# faster 

In [49]:
x = range(10000000)
y = range(10000000, 20000000)
start_time = time.time()
c = [(x,y) for x,y in zip(x,y)]
print(time.time() - start_time)

1.1966030597686768


In [50]:
a =np. arange(10000000)
b =np. arange(10000000, 20000000)
start_time = time.time()
d = a + b
print(time.time() - start_time)

0.022809505462646484


# Indexing Slicing Iteration

In [55]:
arr12 = np.arange(24).reshape(6,4)
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [60]:
arr12[:, 2]

array([ 2,  6, 10, 14, 18, 22])

In [61]:
arr12[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [63]:
arr12[2:4, 1:3]

array([[ 9, 10],
       [13, 14]])

# Numpy operation
# Basic Operation
1. A-b
2. b*2
3. a<35
4. A*B(Element-Wise mul)
5. A.dot(B)
6. A*=B
# Converting type
1. A.astype('float')
# Unary Operations
1. A.min()/A.min()
2. A.sum(axis=0)    //column wise
3. A.max(axis=1)     //row wise
# Universal Functions
1. np.exp(B)
2. np.sqrt()
3. np.sin(A)


In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5,6])
arr2 = np.array([4,5,6,7,8,9])

In [3]:
arr1 - arr2

array([-3, -3, -3, -3, -3, -3])

In [4]:
arr1 * arr2

array([ 4, 10, 18, 28, 40, 54])

In [5]:
arr1 * 2

array([ 2,  4,  6,  8, 10, 12])

In [7]:
arr2 > 5

array([False, False,  True,  True,  True,  True])

In [9]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [10]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [23]:
arr5 = np.array([[4,2,5,6],[5,6,8,5],[6,3,6,9],[9,5,2,5]])
arr5

array([[4, 2, 5, 6],
       [5, 6, 8, 5],
       [6, 3, 6, 9],
       [9, 5, 2, 5]])

In [24]:
arr5

array([[4, 2, 5, 6],
       [5, 6, 8, 5],
       [6, 3, 6, 9],
       [9, 5, 2, 5]])

In [25]:
arr5.max()

np.int64(9)

In [28]:
arr5.min(axis = 0)

array([4, 2, 2, 5])

In [18]:
arr4.sum()

np.int64(51)

# Reshaping Numpy
1. Ravel
2. Reshape
3. Transpose
4. Stacking
5. Splitting

In [30]:
arr5.ravel()

array([4, 2, 5, 6, 5, 6, 8, 5, 6, 3, 6, 9, 9, 5, 2, 5])

In [31]:
arr4.transpose()

array([[ 6,  8, 10],
       [ 7,  9, 11]])

In [33]:
arr6 = np.arange(5, 20).reshape(3,5)
arr7 = np.arange(7, 22).reshape(3,5)

In [34]:
np.hstack((arr6, arr7))


array([[ 5,  6,  7,  8,  9,  7,  8,  9, 10, 11],
       [10, 11, 12, 13, 14, 12, 13, 14, 15, 16],
       [15, 16, 17, 18, 19, 17, 18, 19, 20, 21]])

In [35]:
np.vstack((arr6, arr7))

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [ 7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21]])

# Fancy indexing in numpy

In [36]:
arr8 = np.arange(24).reshape(6,4)
arr8

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [37]:
arr8[[0,2,4]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [16, 17, 18, 19]])

# Indexing with Boolean arrays

In [44]:
arr9 = np.random.randint(low=1, high=100, size=20).reshape(4,5)
arr9

array([[78, 50, 88, 87, 61],
       [90, 97, 18, 75, 59],
       [66, 14,  8, 41, 50],
       [60, 12, 74, 30, 43]], dtype=int32)

In [45]:
arr9[arr9>50]

array([78, 88, 87, 61, 90, 97, 75, 59, 66, 60, 74], dtype=int32)

In [46]:
arr9[(arr9>50) & (arr9%2!=0)]

array([87, 61, 97, 75, 59], dtype=int32)

In [48]:
arr9[(arr9>50) & (arr9%2!=0)]=0
arr9

array([[78, 50, 88,  0,  0],
       [90,  0, 18,  0,  0],
       [66, 14,  8, 41, 50],
       [60, 12, 74, 30, 43]], dtype=int32)