# creating numpy / n-d arrays

In [16]:
import numpy as np

In [17]:
array1 = np.array([1, 2, 3, 4, 5])

In [18]:
array1

array([1, 2, 3, 4, 5])

In [19]:
type(array1)

numpy.ndarray

In [20]:
arr2 = np.array([[1,2,3], [3,4,5]])
arr2

array([[1, 2, 3],
       [3, 4, 5]])

In [21]:
type(arr2)

numpy.ndarray

In [22]:
arr3 = np.zeros((2,3))
arr3

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr4 = np.ones((3,4))
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
arr5 = np.identity(5)
arr5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
arr6 = np.arange(5,16,2)
arr6

array([ 5,  7,  9, 11, 13, 15])

In [26]:
arr7 = np.linspace(10,20,10)
arr7

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

## properties & Attributes
# 1.Shape
# 2.nDim
# 3.size
# 4.Itemsize
# 5.Dtype
# 6.astype()

# Shape

In [27]:
array1.shape


(5,)

In [30]:
arr9 = np.array(([[[1,2], [3,4]], [[5,6], [7,8]]]))
arr9

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [31]:
arr9.shape

(2, 2, 2)

# nDim

In [32]:
arr9.ndim

3

# Size

In [33]:
arr9.size

8

In [34]:
arr7.size

10

# Item size

In [35]:
arr9.itemsize

8

In [36]:
arr7.itemsize

8

# Dtype

In [37]:
arr9.dtype

dtype('int64')

# astype

In [38]:
arr9.astype('float')

array([[[1., 2.],
        [3., 4.]],

       [[5., 6.],
        [7., 8.]]])

# Numpy array vs Python array

# List vs Array
1. Faster
2. Convenient
3. Less memory